part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const PROFILE = _Paths.PROFILE;
  static const AUTH = _Paths.AUTH;
  static const BRANCH_LIST = _Paths.BRANCH_LIST;
  static const USERS = _Paths.USERS;
  static const SPARE_CATEGORY = _Paths.SPARE_CATEGORY;
  static const WORK = _Paths.WORK;
  static const CATEGORY_LIST = _Paths.CATEGORY_LIST;
  static const SERVICE_LIST = _Paths.SERVICE_LIST;
  static const PACKAGE_LIST = _Paths.PACKAGE_LIST;
  static const ADD_BRANCH = _Paths.ADD_BRANCH;
  static const ADD_CATEGORY = _Paths.ADD_CATEGORY;
  static const ADD_PACKAGE = _Paths.ADD_PACKAGE;
  static const ADD_SERVICE = _Paths.ADD_SERVICE;
  static const ADD_SPARE_CATEGORY = _Paths.ADD_SPARE_CATEGORY;
  static const SPARE = _Paths.SPARE;
  static const ADD_SPARE = _Paths.ADD_SPARE;
  static const ADD_USERS = _Paths.ADD_USERS;
  static const ADD_WORK = _Paths.ADD_WORK;
  static const VEHICLE = _Paths.VEHICLE;
  static const ADD_BRAND = _Paths.ADD_BRAND;
  static const ADD_COLOR_PAGE = _Paths.ADD_COLOR_PAGE;
  static const ADD_YEAR_PAGE = _Paths.ADD_YEAR_PAGE;
  static const SERVICE_MODE = _Paths.SERVICE_MODE;
  static const ADD_SERVICE_MODE = _Paths.ADD_SERVICE_MODE;
  static const TIME_SLOTS = _Paths.TIME_SLOTS;
  static const SPLASH_PAGE = _Paths.SPLASH_PAGE;
  static const VARIANT = _Paths.VARIANT;
  static const ADD_VARIANT = _Paths.ADD_VARIANT;
  static const CAR_MODEL = _Paths.CAR_MODEL;
  static const ADD_CAR_MODEL = _Paths.ADD_CAR_MODEL;
  static const BANNER = _Paths.BANNER;
  static const ADD_BANNER = _Paths.ADD_BANNER;
  static const CUSTOM_PRICE = _Paths.CUSTOM_PRICE;
  static const MAP_PAGE = _Paths.MAP_PAGE;
  static const COUPON = _Paths.COUPON;
  static const ADD_COUPON = _Paths.ADD_COUPON;
  static const REWARD = _Paths.REWARD;
  static const UPLOAD_COUPON = _Paths.UPLOAD_COUPON;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const PROFILE = '/profile';
  static const AUTH = '/auth';
  static const BRANCH_LIST = '/branch-list';
  static const USERS = '/users';
  static const SPARE_CATEGORY = '/spare-category';
  static const WORK = '/work';
  static const CATEGORY_LIST = '/category-list';
  static const SERVICE_LIST = '/service-list';
  static const PACKAGE_LIST = '/package-list';
  static const ADD_BRANCH = '/add-branch';
  static const ADD_CATEGORY = '/add-category';
  static const ADD_PACKAGE = '/add-package';
  static const ADD_SERVICE = '/add-service';
  static const ADD_SPARE_CATEGORY = '/add-spare-category';
  static const SPARE = '/spare';
  static const ADD_SPARE = '/add-spare';
  static const ADD_USERS = '/add-users';
  static const ADD_WORK = '/add-work';
  static const VEHICLE = '/vehicle';
  static const ADD_BRAND = '/add-brand';
  static const ADD_COLOR_PAGE = '/add-color-page';
  static const ADD_YEAR_PAGE = '/add-year-page';
  static const SERVICE_MODE = '/service-mode';
  static const ADD_SERVICE_MODE = '/add-service-mode';
  static const TIME_SLOTS = '/time-slots';
  static const SPLASH_PAGE = '/splash-page';
  static const VARIANT = '/variant';
  static const ADD_VARIANT = '/add-variant';
  static const CAR_MODEL = '/car-model';
  static const ADD_CAR_MODEL = '/add-car-model';
  static const BANNER = '/banner';
  static const ADD_BANNER = '/add-banner';
  static const CUSTOM_PRICE = '/custom-price';
  static const MAP_PAGE = '/map-page';
  static const COUPON = '/coupon';
  static const ADD_COUPON = '/add-coupon';
  static const REWARD = '/reward';
  static const UPLOAD_COUPON = '/upload-coupon';
}
